SUBGENRE_PROFILES = {
    "general": {
        "name": "General",
        "apply_subgenre_analysis": False,
    },
    "heavy_dubstep": {
        "name": "Heavy Dubstep",
        "reference_artists": "Excision, Subtronics",
        "typical_bpm": [145, 150],
        "feel": "Half-time at 150 BPM (sometimes 145)",
        "drums": "Sparse in the drop — kick and snare on 1 and 3, lots of space for the bass to breathe",
        "bass": "Layered sub + mid-range growls/screeches, metallic/robotic textures, heavy use of wobbles, formant shifts, and 'talking' basses",
        "leads": "Aggressive mid-range bass leads dominate; melodic leads are rare",
        "mix": "Wide stereo on mids and highs, mono sub bass, very loud and dense",
        "structure": "Long buildups with risers, hard drops with maximum impact",
    },
    "trap": {
        "name": "Trap",
        "reference_artists": "RL Grime, ISOXO, TRXGG",
        "typical_bpm": [140, 160],
        "feel": "Half-time feel — feels slower than the actual BPM",
        "drums": "808s as the foundation (long, sliding, sometimes distorted), hi-hat rolls and triplet patterns, snares often have heavy reverb tails",
        "bass": "808-driven bass; tuned and melodic, often pitched to the key",
        "leads": "Airy and noisy leads with distinctive rhythmic patterns; atmospheric pads, vocal chops, ethereal textures",
        "mix": "More melodic and atmospheric than dubstep; spacious with strong reverb use",
        "structure": "Builds around vocal or melodic hooks; drops emphasize 808 + lead interplay",
    },
    "melodic_bass": {
        "name": "Melodic Bass",
        "reference_artists": "Illenium, Roy Knox",
        "typical_bpm": [140, 155],
        "feel": "Half-time feel; emotional and uplifting",
        "drums": "Standard bass music drum patterns; punchy kick and snare with melodic context",
        "bass": "Melodic basses (not just growls) — saw leads, plucks, supersaws drive the drop",
        "leads": "Emotional chord progressions, often piano/guitar-driven intros; vocal-forward production with strong toplines",
        "mix": "Wide and lush — heavy reverb, sidechained pads, polished and emotional",
        "structure": "Strong emphasis on melody and harmony; vocal-driven verses leading into melodic drops",
    },
    "bass_house": {
        "name": "Bass House",
        "reference_artists": "Knock2, Ray Volpe, Crankdat",
        "typical_bpm": [126, 130],
        "feel": "Four-on-the-floor, driving and bouncy",
        "drums": "4-on-the-floor kick pattern (unlike dubstep/trap), tight and punchy",
        "bass": "Bouncy, groovy basslines — often G-house influenced growls but cleaner and tighter than dubstep",
        "leads": "Bass-forward; leads are usually the bass itself with house-style stabs",
        "mix": "Tighter, punchier mix than melodic bass; club-ready loudness",
        "structure": "House structure with bass music drops — drops feel like house but with bass-music sound design",
    },
    "speed_garage": {
        "name": "Speed Garage",
        "reference_artists": "Classic UK garage with modern bass influence",
        "typical_bpm": [130, 140],
        "feel": "UK garage swing feel — shuffled 2-step or 4-on-the-floor with offbeat hats",
        "drums": "Shuffled 2-step patterns or 4-on-floor with prominent offbeat hi-hats",
        "bass": "Reese basses, sub-heavy, often with movement and modulation",
        "leads": "Vocal chops (often pitched), stabs, and atmospheric elements",
        "mix": "Less 'wall of sound' than dubstep; more groove-focused, punchy and clear",
        "structure": "Groove-driven; emphasis on rhythm and bass movement over big drops",
    },
}
